// Generated by CoffeeScript 1.8.0
var AssetDigest;

AssetDigest = (function() {
  AssetDigest.prototype.brunchPlugin = true;

  function AssetDigest(config) {
    this.config = config;
    null;
  }

  return AssetDigest;

})();

module.exports = AssetDigest;
